In [ ]:
# STUDENT PERFORMANCE - MACHINE LEARNING

# 1. Import Libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
# 2. LOAD DATA
df = pd.read_csv("student_performance.csv")

print("Original Data:")
print(df.head())

print("\nShape:")
print(df.shape)


Original Data:
   Student_ID  Study_Hours  Attendance  Previous_Score  Assignments_Completed  \
0           1          7.0        58.0            66.0                    3.0   
1           2          4.0        83.0            74.0                    3.0   
2           3          8.0        72.0            40.0                    5.0   
3           4          5.0        80.0            74.0                    8.0   
4           5          7.0        98.0            76.0                    3.0   

   Final_Score  
0           52  
1           42  
2           46  
3           57  
4           53  

Shape:
(60, 6)


In [ ]:
# 3. DATA CLEANING

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Fill missing numerical values with column mean
df["Study_Hours"] = df["Study_Hours"].fillna(
    df["Study_Hours"].mean()
)

df["Attendance"] = df["Attendance"].fillna(
    df["Attendance"].mean()
)

df["Previous_Score"] = df["Previous_Score"].fillna(
    df["Previous_Score"].mean()
)

df["Assignments_Completed"] = df["Assignments_Completed"].fillna(
    df["Assignments_Completed"].mean()
)

print("\nMissing Values After Cleaning:")
print(df.isnull().sum())



Missing Values:
Student_ID               0
Study_Hours              2
Attendance               2
Previous_Score           1
Assignments_Completed    1
Final_Score              0
dtype: int64

Missing Values After Cleaning:
Student_ID               0
Study_Hours              0
Attendance               0
Previous_Score           0
Assignments_Completed    0
Final_Score              0
dtype: int64


In [ ]:
# 4. INPUT AND TARGET

# Input features
X = df[
    [
        "Study_Hours",
        "Attendance",
        "Previous_Score",
        "Assignments_Completed"
    ]
]

# Target variable
y = df["Final_Score"]

print("\nInput X:")
print(X)

print("\nTarget y:")
print(y)



Input X:
    Study_Hours  Attendance  Previous_Score  Assignments_Completed
0      7.000000   58.000000       66.000000               3.000000
1      4.000000   83.000000       74.000000               3.000000
2      8.000000   72.000000       40.000000               5.000000
3      5.000000   80.000000       74.000000               8.000000
4      7.000000   98.000000       76.000000               3.000000
5      5.517241   88.000000       86.000000               6.000000
6      3.000000   64.000000       53.000000               7.000000
7      7.000000   90.000000       42.000000               3.000000
8      8.000000   68.000000       40.000000               5.000000
9      5.000000   85.000000       44.000000               9.000000
10     4.000000   69.000000       65.000000               8.000000
11     8.000000   62.000000       94.000000              10.000000
12     8.000000   68.000000       53.000000               5.000000
13     3.000000   77.000000       78.000000         

In [ ]:
# 5. RESHAPE

# Convert X and y into NumPy arrays
X = np.array(X)
y = np.array(y)

print("\nX Shape:", X.shape)
print("y Shape:", y.shape)



X Shape: (60, 4)
y Shape: (60,)


In [ ]:
# 6. TRAIN-TEST SPLIT


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("\nTraining Input Shape:", X_train.shape)
print("Testing Input Shape:", X_test.shape)

print("Training Target Shape:", y_train.shape)
print("Testing Target Shape:", y_test.shape)




Training Input Shape: (48, 4)
Testing Input Shape: (12, 4)
Training Target Shape: (48,)
Testing Target Shape: (12,)


In [ ]:
# 7. MODEL IMPLEMENTATION

model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

print("\nModel Training Completed")



Model Training Completed


In [ ]:
# 8. MAKE PREDICTION


y_pred = model.predict(X_test)

print("\nActual Values:")
print(y_test)

print("\nPredicted Values:")
print(y_pred)



Actual Values:
[52 66 61 54 42 46 48 53 50 63 49 49]

Predicted Values:
[44.96041257 59.66563973 64.27446398 54.13952791 44.2833606  48.18393557
 49.60063048 52.14651285 50.24778751 54.18077125 48.6325131  54.2044058 ]


In [ ]:
# 9. PREDICT FOR A NEW STUDENT

# New student:
# Study Hours = 6
# Attendance = 90
# Previous Score = 75
# Assignments Completed = 9

new_student = np.array([
    [6, 90, 75, 9]
])

prediction = model.predict(new_student)

print("\nNew Student Predicted Final Score:")
print(prediction[0])



New Student Predicted Final Score:
64.31665920843946


In [ ]:
# 10. MODEL EVALUATION

# Calculate prediction error
error = np.abs(y_test - y_pred)

# Accuracy for each student
accuracy = 100 - (error / y_test * 100)

# Average accuracy
average_accuracy = np.mean(accuracy)

print("Accuracy for each student:")
print(accuracy)

print("\nAverage Accuracy:", average_accuracy, "%")

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("\nMean Squared Error:", mse)
print("R2 Score:", r2)

Accuracy for each student:
[86.46233186 90.40248444 94.63202626 99.74161498 94.56342715 95.25231398
 96.66535318 98.38964689 99.50442498 86.0012242  99.25002673 89.37876367]

Average Accuracy: 94.18696985991114 %

Mean Squared Error: 18.2296952407384
R2 Score: 0.6163851944079599


In [38]:
# ==========================================
# DECISION TREE - MACHINE FAILURE PREDICTION
# ==========================================

# 1. Import libraries

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report




In [39]:
# ==========================================
# 2. LOAD DATASET
# ==========================================

df = pd.read_csv("factory_machine_failure_prediction.csv")

print("Dataset:")
print(df.head())

print("\nDataset Shape:")
print(df.shape)




Dataset:
  Machine_ID  Temperature_C  Vibration_mm_s  Pressure_psi   RPM  \
0       M001           59.0            2.98         126.0  1906   
1       M002           80.0            2.76         103.0  2085   
2       M003           58.0            7.87          91.0  1879   
3       M004           74.0            3.97          91.0  1155   
4       M005           78.0            3.85         100.0  1476   

   Operating_Hours  Machine_Failure  
0           1400.0                0  
1            911.0                1  
2           2332.0                1  
3           2809.0                0  
4           2070.0                0  

Dataset Shape:
(60, 7)


In [40]:

# ==========================================
# 3. CHECK DATA
# ==========================================

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDataset Information:")
print(df.info())



Missing Values:
Machine_ID         0
Temperature_C      1
Vibration_mm_s     1
Pressure_psi       1
RPM                0
Operating_Hours    1
Machine_Failure    0
dtype: int64

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Machine_ID       60 non-null     object 
 1   Temperature_C    59 non-null     float64
 2   Vibration_mm_s   59 non-null     float64
 3   Pressure_psi     59 non-null     float64
 4   RPM              60 non-null     int64  
 5   Operating_Hours  59 non-null     float64
 6   Machine_Failure  60 non-null     int64  
dtypes: float64(4), int64(2), object(1)
memory usage: 3.4+ KB
None


In [41]:

# ==========================================
# 4. DATA CLEANING
# ==========================================

# Fill missing numerical values with mean

numeric_columns = [
    "Temperature_C",
    "Vibration_mm_s",
    "Pressure_psi",
    "RPM",
    "Operating_Hours"
]

for column in numeric_columns:
    df[column] = df[column].fillna(df[column].mean())


print("\nMissing Values After Cleaning:")
print(df.isnull().sum())



Missing Values After Cleaning:
Machine_ID         0
Temperature_C      0
Vibration_mm_s     0
Pressure_psi       0
RPM                0
Operating_Hours    0
Machine_Failure    0
dtype: int64


In [42]:

# ==========================================
# 5. INPUT AND TARGET
# ==========================================

X = df[
    [
        "Temperature_C",
        "Vibration_mm_s",
        "Pressure_psi",
        "RPM",
        "Operating_Hours"
    ]
]

y = df["Machine_Failure"]


print("\nInput X:")
print(X.head())

print("\nTarget y:")
print(y.head())



Input X:
   Temperature_C  Vibration_mm_s  Pressure_psi   RPM  Operating_Hours
0           59.0            2.98         126.0  1906           1400.0
1           80.0            2.76         103.0  2085            911.0
2           58.0            7.87          91.0  1879           2332.0
3           74.0            3.97          91.0  1155           2809.0
4           78.0            3.85         100.0  1476           2070.0

Target y:
0    0
1    1
2    1
3    0
4    0
Name: Machine_Failure, dtype: int64


In [43]:
# ==========================================
# 6. CONVERT TO NUMPY
# ==========================================

X = np.array(X)
y = np.array(y)

print("\nX Shape:", X.shape)
print("y Shape:", y.shape)



X Shape: (60, 5)
y Shape: (60,)


In [44]:


# ==========================================
# 7. TRAIN-TEST SPLIT
# ==========================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining Data:", X_train.shape)
print("Testing Data:", X_test.shape)


Training Data: (48, 5)
Testing Data: (12, 5)


In [45]:
# ==========================================
# 8. CREATE DECISION TREE MODEL
# ==========================================

model = DecisionTreeClassifier(
    criterion="gini",
    max_depth=4,
    random_state=42
)


In [46]:

# ==========================================
# 9. TRAIN MODEL
# ==========================================

model.fit(X_train, y_train)

print("\nDecision Tree Model Training Completed")


Decision Tree Model Training Completed


In [47]:
# ==========================================
# 10. MAKE PREDICTION
# ==========================================

y_pred = model.predict(X_test)

print("\nActual Values:")
print(y_test)

print("\nPredicted Values:")
print(y_pred)



Actual Values:
[0 1 1 0 1 0 1 0 0 0 1 0]

Predicted Values:
[0 1 0 1 1 0 0 1 0 1 0 1]


In [48]:

# ==========================================
# 11. ACCURACY
# ==========================================

accuracy = accuracy_score(y_test, y_pred)

print("\nModel Accuracy:", accuracy * 100, "%")



Model Accuracy: 41.66666666666667 %


In [49]:


# ==========================================
# 12. CONFUSION MATRIX
# ==========================================

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:")
print(cm)


Confusion Matrix:
[[3 4]
 [3 2]]


In [50]:

# ==========================================
# 13. CLASSIFICATION REPORT
# ==========================================

print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       0.50      0.43      0.46         7
           1       0.33      0.40      0.36         5

    accuracy                           0.42        12
   macro avg       0.42      0.41      0.41        12
weighted avg       0.43      0.42      0.42        12



In [51]:
# ==========================================
# 14. PREDICT A NEW MACHINE
# ==========================================

# New machine:
# Temperature = 90 C
# Vibration = 7.2 mm/s
# Pressure = 80 psi
# RPM = 1950
# Operating Hours = 4500

new_machine = np.array([
    [90, 7.2, 80, 1950, 4500]
])

prediction = model.predict(new_machine)

print("\nNew Machine Prediction:")

if prediction[0] == 1:
    print("Machine Failure: YES")
else:
    print("Machine Failure: NO")


New Machine Prediction:
Machine Failure: YES


In [52]:

# ==========================================
# 15. FAILURE PROBABILITY
# ==========================================

probability = model.predict_proba(new_machine)

print("\nFailure Probability:",
      probability[0][1] * 100, "%")


Failure Probability: 100.0 %
